#!/bin/bash

dir=$( cd "$( dirname "$0" )" && pwd )/files

if [ $# -ne 1 ]; then
	echo "${0##*/} <project-name>"
	exit 1
fi

if [ -d $1 ]; then
	ech "$1 directory already exists"
	exit 2
fi

#
#
#
echo "creating directories..."

mkdir $1
mkdir $1/build
mkdir $1/src
mkdir $1/inc

#
#
#
echo "copying blank project files..."

p_guid=`$dir/uuidgen.exe`
i_guid=`$dir/uuidgen.exe`
s_guid=`$dir/uuidgen.exe`

sed -e "s/p-guid/$p_guid/" \
    < $dir/static-lib.vcxproj \
    > $1/build/$1.vcxproj

sed -e "s/i-guid/$i_guid/" \
    -e "s/s-guid/$s_guid/" \
    < $dir/static-lib.vcxproj.filters \
    > $1/build/$1.vcxproj.filters

#
#
#
echo "initializing git repo..."

pushd $1 > /dev/null
git init -q
cp $dir/.gitignore .
git add .gitignore build/* >/dev/null 2>&1
popd > /dev/null

#
#
#
echo "done"
