#!/bin/bash

dir=$( cd "$( dirname "$0" )" && pwd )/files

if [ $# -ne 1 ]; then
	echo "${0##*/} <project-name>"
	exit 1
fi

if [ -d $1 ]; then
	ech "$1 directory already exists"
	exit 2
fi

#
#
#
echo "creating directories..."

mkdir $1
mkdir $1/build
mkdir $1/src

#
#
#
echo "copying blank project files..."

p_guid=`$dir/uuidgen.exe`

sed -e "s/p-guid/$p_guid/" \
    < $dir/window-app.vcxproj \
    > $1/build/$1.vcxproj

cp $dir/main.cpp $1/src

#
#
#
echo "initializing git repo..."

git init $1 -q
cp $dir/.gitignore $1

#
#
#
echo "done"
